version: '3.1'
services:
  app:
    container_name: moneta-customer-service
    build: ./
    ports:
      - "8090:8090"
    depends_on:
      - dbpostgresql
  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=postgres
      - POSTGRES_DB=customerdb