spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/customerdb
    username: postgres
    password: pass

logging:
  level:
    org.springframework.data.r2dbc: Debug



---
spring:
  profiles: docker
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/customerdb
    username: postgres
    password: pass